twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        GOOGLE_ANALYTICS_ID: '%env(GOOGLE_ANALYTICS_ID)%'
        supported_locales: '%supported_locales%'