controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        # must conform with supported_locales parameters
        _locale: en|uk|ru

front:
    resource: ../../src/Controller/FrontController.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
